-- Taslaafa: all migrations, in order.
-- Paste this whole file into the Supabase SQL Editor and press Run.
-- Generated from supabase/migrations/ -- do not edit this file directly.

-- ============================================================
-- 0001_schema.sql
-- ============================================================
-- Taslaafa 0001: core schema
-- All timestamps are timestamptz, stored UTC. Rendering in +05 is a client concern.

create extension if not exists pgcrypto;

create type public.user_role as enum ('owner', 'staff', 'driver');

create type public.event_type as enum (
  'created',          -- order taken at the shop
  'sent_out',         -- left the shop
  'link_opened',      -- customer opened /d/[token] (written once)
  'code_attempted',   -- driver typed a code; payload.ok true/false
  'code_confirmed',   -- handed over
  'marked_late',      -- swept past sent_at + promise_minutes
  'problem_reported', -- customer tapped "Report a problem": preset reason + optional note
  'code_reissued'     -- owner minted a fresh code after a lock
);

create type public.actor_kind as enum ('owner', 'staff', 'driver', 'customer', 'system');


-- ---------------------------------------------------------------- shop
create table public.shop (
  id                      uuid primary key default gen_random_uuid(),
  name                    text not null check (length(btrim(name)) > 0),
  branch                  text,
  timezone                text not null default 'Indian/Maldives',
  default_promise_minutes smallint not null default 30
                            check (default_promise_minutes in (15, 30, 45, 60)),
  created_at              timestamptz not null default now()
);


-- ------------------------------------------------------------ app_user
-- PK is the Supabase auth user id: one auth identity, one shop, one role.
create table public.app_user (
  id         uuid primary key references auth.users (id) on delete cascade,
  shop_id    uuid not null references public.shop (id) on delete restrict,
  role       public.user_role not null,
  full_name  text not null check (length(btrim(full_name)) > 0),
  phone      text check (phone ~ '^\+960[0-9]{7}$'),
  is_active  boolean not null default true,
  created_at timestamptz not null default now()
);

create index app_user_shop_idx on public.app_user (shop_id) where is_active;


-- ------------------------------------------------------------ customer
-- Addresses here are house names, not street numbers. Free text, never parsed.
create table public.customer (
  id         uuid primary key default gen_random_uuid(),
  shop_id    uuid not null references public.shop (id) on delete restrict,
  name       text not null check (length(btrim(name)) > 0),
  phone      text not null check (phone ~ '^\+960[0-9]{7}$'),
  address    text not null check (length(btrim(address)) > 0),
  created_at timestamptz not null default now(),
  unique (shop_id, phone)
);

create index customer_shop_name_idx on public.customer (shop_id, lower(name));


-- ------------------------------------------------------------ delivery
create table public.delivery (
  id              uuid primary key default gen_random_uuid(),
  shop_id         uuid not null references public.shop (id) on delete restrict,
  customer_id     uuid not null references public.customer (id) on delete restrict,
  order_ref       text,
  promise_minutes smallint not null check (promise_minutes in (15, 30, 45, 60)),
  driver_id       uuid references public.app_user (id) on delete restrict,
  created_by      uuid references public.app_user (id) on delete restrict,
  public_token    text not null unique check (public_token ~ '^[A-Za-z0-9_-]{22,64}$'),
  created_at      timestamptz not null default now(),
  sent_at         timestamptz,
  -- Written at send time. Not a generated column: timestamptz + interval is
  -- STABLE, not IMMUTABLE, so Postgres will not store it for us.
  due_at          timestamptz,
  confirmed_at    timestamptz,
  confirmed_by    uuid references public.app_user (id) on delete restrict,
  constraint delivery_due_with_sent check ((sent_at is null) = (due_at is null)),
  constraint delivery_confirmed_after_sent check (confirmed_at is null or sent_at is not null)
);

create index delivery_board_idx on public.delivery (shop_id, created_at desc);
create index delivery_open_idx  on public.delivery (shop_id, due_at)
  where confirmed_at is null and sent_at is not null;
create index delivery_driver_idx on public.delivery (driver_id, created_at desc);


-- ------------------------------------------------------- delivery_code
-- Rule 2: nobody at the shop can read a code.
--   code_hash = HMAC-SHA256(mac_key, code)     -> used to verify an attempt
--   code_ct   = AES-256-GCM(enc_key, code)     -> decrypted ONLY by /d/[token]
-- Both keys are HKDF-derived from TASLAAFA_CODE_KEY, which lives in the app
-- environment and never enters the database. A full DB dump therefore reveals
-- no code and cannot brute-force one, despite there being only 10,000.
create table public.delivery_code (
  delivery_id uuid primary key references public.delivery (id) on delete restrict,
  code_hash   text not null,
  code_ct     text not null,
  key_version smallint not null default 1,
  attempts    smallint not null default 0 check (attempts between 0 and 3),
  locked      boolean not null default false,
  reissues    smallint not null default 0,
  created_at  timestamptz not null default now()
);


-- ------------------------------------------------------ delivery_event
-- Rule 1: append-only. See 0002 for the enforcement.
create table public.delivery_event (
  id            bigint generated always as identity primary key,
  delivery_id   uuid not null references public.delivery (id) on delete restrict,
  shop_id       uuid not null references public.shop (id) on delete restrict,
  type          public.event_type not null,
  actor_kind    public.actor_kind not null,
  actor_user_id uuid references public.app_user (id) on delete restrict,
  payload       jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now(),
  -- a staff/driver/owner event must name its actor; customer and system never do
  constraint delivery_event_actor_shape check (
    (actor_kind in ('owner', 'staff', 'driver')) = (actor_user_id is not null)
  )
);

create index delivery_event_timeline_idx on public.delivery_event (delivery_id, created_at, id);
create index delivery_event_shop_idx     on public.delivery_event (shop_id, created_at desc);

-- One link_opened per delivery, enforced by the database rather than by a check
-- in the route handler.
create unique index delivery_event_one_open_idx
  on public.delivery_event (delivery_id)
  where type = 'link_opened';

-- ============================================================
-- 0002_append_only_and_grants.sql
-- ============================================================
-- Taslaafa 0002: rule 1 (append-only log) and the privilege baseline.

-- ------------------------------------------- append-only delivery_event
-- RLS alone is not enough: service_role has BYPASSRLS, and every write in this
-- app goes through service_role. A trigger does not get bypassed, so that is
-- what actually holds the line.
create or replace function public.forbid_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception '% is append-only; % is not permitted', tg_table_name, tg_op
    using errcode = '42501',
          hint = 'Record the correction as a new delivery_event row.';
end;
$$;

create trigger delivery_event_no_update
  before update on public.delivery_event
  for each row execute function public.forbid_mutation();

create trigger delivery_event_no_delete
  before delete on public.delivery_event
  for each row execute function public.forbid_mutation();

create trigger delivery_event_no_truncate
  before truncate on public.delivery_event
  for each statement execute function public.forbid_mutation();

-- A delete on delivery would orphan its proof, so delivery is immutable in the
-- same way for DELETE only. UPDATE stays allowed (sent_at, confirmed_at...).
create trigger delivery_no_delete
  before delete on public.delivery
  for each row execute function public.forbid_mutation();

create trigger delivery_no_truncate
  before truncate on public.delivery
  for each statement execute function public.forbid_mutation();


-- --------------------------------------------------------------- grants
-- Supabase grants broadly by default. Start from nothing.
revoke all on all tables in schema public from anon, authenticated;

-- The customer has no account and never touches Postgres directly: /d/[token]
-- is served by a route handler. anon keeps zero table access.

-- Authenticated clients are READ-ONLY. Every write goes through a server route
-- that checks the session and then uses service_role, so the write path is one
-- reviewable surface instead of a policy matrix.
grant select on public.shop, public.app_user, public.customer,
                public.delivery, public.delivery_event
  to authenticated;

-- delivery_code is granted to no one. Not anon, not authenticated. It is
-- reachable only by service_role, and only from src/server/codes.ts.

-- Even service_role cannot rewrite history.
revoke update, delete, truncate on public.delivery_event from service_role;
revoke delete, truncate on public.delivery from service_role;


-- ------------------------------------------------------------- RLS base
alter table public.shop           enable row level security;
alter table public.app_user       enable row level security;
alter table public.customer       enable row level security;
alter table public.delivery       enable row level security;
alter table public.delivery_code  enable row level security;
alter table public.delivery_event enable row level security;

-- FORCE so the table owner is subject to policies too.
alter table public.shop           force row level security;
alter table public.app_user       force row level security;
alter table public.customer       force row level security;
alter table public.delivery       force row level security;
alter table public.delivery_code  force row level security;
alter table public.delivery_event force row level security;

-- delivery_code deliberately has NO policies. RLS on with zero policies denies
-- every row to every non-bypassing role. Combined with the missing grant, an
-- authenticated client cannot reach a code even if a policy is added by mistake
-- later.


-- -------------------------------------------------- identity helpers
-- SECURITY DEFINER so reading app_user inside a policy on app_user does not
-- recurse. search_path pinned.
create or replace function public.current_shop_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select shop_id from public.app_user where id = auth.uid() and is_active
$$;

create or replace function public.current_role_name()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.app_user where id = auth.uid() and is_active
$$;

revoke execute on function public.current_shop_id()   from public, anon;
revoke execute on function public.current_role_name() from public, anon;
grant  execute on function public.current_shop_id()   to authenticated;
grant  execute on function public.current_role_name() to authenticated;


-- ------------------------------------------------------------ policies
create policy shop_read on public.shop
  for select to authenticated
  using (id = public.current_shop_id());

create policy app_user_read on public.app_user
  for select to authenticated
  using (shop_id = public.current_shop_id());

-- Owner and staff see the whole customer book. A driver sees only the customers
-- behind his own drops.
create policy customer_read on public.customer
  for select to authenticated
  using (
    shop_id = public.current_shop_id()
    and (
      public.current_role_name() in ('owner', 'staff')
      or exists (
        select 1 from public.delivery d
        where d.customer_id = customer.id
          and d.driver_id = auth.uid()
      )
    )
  );

create policy delivery_read on public.delivery
  for select to authenticated
  using (
    shop_id = public.current_shop_id()
    and (
      public.current_role_name() in ('owner', 'staff')
      or driver_id = auth.uid()
    )
  );

create policy delivery_event_read on public.delivery_event
  for select to authenticated
  using (
    shop_id = public.current_shop_id()
    and (
      public.current_role_name() in ('owner', 'staff')
      or exists (
        select 1 from public.delivery d
        where d.id = delivery_event.delivery_id
          and d.driver_id = auth.uid()
      )
    )
  );

-- ============================================================
-- 0003_functions.sql
-- ============================================================
-- Taslaafa 0003: the three writes that must be atomic.
--
-- These are SECURITY INVOKER on purpose. They are executable only by
-- service_role, which has BYPASSRLS, so they run with exactly the privileges
-- the server already has -- no privilege escalation hidden in a definer.
-- The append-only triggers still apply to them.

-- Makes the late sweep idempotent without a read-then-write race.
create unique index delivery_event_one_late_idx
  on public.delivery_event (delivery_id)
  where type = 'marked_late';


-- ----------------------------------------------------- attempt_code
-- The app computes HMAC-SHA256(mac_key, typed_code) and passes the hex digest.
-- The key never reaches Postgres, so this function cannot be used as an oracle
-- by anyone who only has database access.
--
-- Returns jsonb: { result, attempts, attempts_left, locked, seconds_to_door,
--                  beat_promise, confirmed_at }
-- result is one of: confirmed | wrong | locked | already_confirmed | not_found
create or replace function public.attempt_code(
  p_delivery_id uuid,
  p_actor_id    uuid,
  p_code_hash   text
)
returns jsonb
language plpgsql
as $$
declare
  d        public.delivery%rowtype;
  c        public.delivery_code%rowtype;
  v_ok     boolean;
  v_locked boolean;
  v_secs   integer;
  v_beat   boolean;
begin
  -- Lock the code row first: two taps on a slow connection must not both count.
  select * into c from public.delivery_code
    where delivery_id = p_delivery_id
    for update;

  if not found then
    return jsonb_build_object('result', 'not_found');
  end if;

  select * into d from public.delivery where id = p_delivery_id for update;

  if d.confirmed_at is not null then
    return jsonb_build_object('result', 'already_confirmed',
                              'confirmed_at', d.confirmed_at);
  end if;

  if c.locked then
    return jsonb_build_object('result', 'locked',
                              'attempts', c.attempts, 'attempts_left', 0,
                              'locked', true);
  end if;

  -- Both sides are fixed-length hex digests of a secret-keyed HMAC, so a
  -- timing difference here leaks nothing about the 4 digits.
  v_ok := (c.code_hash = p_code_hash);

  if v_ok then
    update public.delivery
       set confirmed_at = now(), confirmed_by = p_actor_id
     where id = p_delivery_id
    returning * into d;

    v_secs := extract(epoch from (d.confirmed_at - d.sent_at))::integer;
    v_beat := d.confirmed_at <= d.due_at;

    insert into public.delivery_event
      (delivery_id, shop_id, type, actor_kind, actor_user_id, payload)
    values
      (d.id, d.shop_id, 'code_confirmed', 'driver', p_actor_id,
       jsonb_build_object('attempt', c.attempts + 1,
                          'seconds_to_door', v_secs,
                          'beat_promise', v_beat));

    -- The successful attempt is part of the record too.
    insert into public.delivery_event
      (delivery_id, shop_id, type, actor_kind, actor_user_id, payload)
    values
      (d.id, d.shop_id, 'code_attempted', 'driver', p_actor_id,
       jsonb_build_object('ok', true, 'attempt', c.attempts + 1, 'locked', false));

    return jsonb_build_object('result', 'confirmed',
                              'attempts', c.attempts + 1, 'attempts_left', 0,
                              'locked', false,
                              'seconds_to_door', v_secs,
                              'beat_promise', v_beat,
                              'confirmed_at', d.confirmed_at);
  end if;

  v_locked := (c.attempts + 1) >= 3;

  update public.delivery_code
     set attempts = c.attempts + 1,
         locked   = v_locked
   where delivery_id = p_delivery_id;

  -- Written on every miss, so the shop sees a lock the moment it happens.
  insert into public.delivery_event
    (delivery_id, shop_id, type, actor_kind, actor_user_id, payload)
  values
    (p_delivery_id, d.shop_id, 'code_attempted', 'driver', p_actor_id,
     jsonb_build_object('ok', false, 'attempt', c.attempts + 1, 'locked', v_locked));

  return jsonb_build_object('result', case when v_locked then 'locked' else 'wrong' end,
                            'attempts', c.attempts + 1,
                            'attempts_left', greatest(3 - (c.attempts + 1), 0),
                            'locked', v_locked);
end;
$$;


-- ------------------------------------------------- record_link_opened
-- Idempotent: the partial unique index means only the first open is recorded,
-- however many times the customer reloads the page.
create or replace function public.record_link_opened(p_delivery_id uuid)
returns boolean
language plpgsql
as $$
declare
  v_shop uuid;
begin
  select shop_id into v_shop from public.delivery where id = p_delivery_id;
  if not found then
    return false;
  end if;

  insert into public.delivery_event
    (delivery_id, shop_id, type, actor_kind, payload)
  values
    (p_delivery_id, v_shop, 'link_opened', 'customer', '{}'::jsonb)
  on conflict do nothing;

  return true;
end;
$$;


-- -------------------------------------------------------- sweep_late
-- Flags every delivery past sent_at + promise_minutes that is still unconfirmed
-- and not already flagged. Called by the Vercel cron AND by the live-board poll
-- endpoint, so lateness surfaces within ~10s without depending on cron tier.
-- Returns the number newly flagged.
create or replace function public.sweep_late(p_shop_id uuid default null)
returns integer
language sql
as $$
  with overdue as (
    select d.id, d.shop_id, d.due_at
      from public.delivery d
     where d.confirmed_at is null
       and d.sent_at is not null
       and d.due_at < now()
       and (p_shop_id is null or d.shop_id = p_shop_id)
  ), inserted as (
    insert into public.delivery_event
      (delivery_id, shop_id, type, actor_kind, payload)
    select o.id, o.shop_id, 'marked_late', 'system',
           jsonb_build_object('due_at', o.due_at,
                              'minutes_over',
                              floor(extract(epoch from (now() - o.due_at)) / 60)::int)
      from overdue o
    on conflict do nothing
    returning 1
  )
  select coalesce(count(*), 0)::int from inserted;
$$;


-- Server-only. No authenticated client may call these.
revoke execute on function public.attempt_code(uuid, uuid, text)  from public, anon, authenticated;
revoke execute on function public.record_link_opened(uuid)        from public, anon, authenticated;
revoke execute on function public.sweep_late(uuid)                from public, anon, authenticated;
grant  execute on function public.attempt_code(uuid, uuid, text)  to service_role;
grant  execute on function public.record_link_opened(uuid)        to service_role;
grant  execute on function public.sweep_late(uuid)                to service_role;


-- ------------------------------------------------------ reissue_code
-- Owner only, and only by way of /api/deliveries/[id]/reissue, which checks the
-- role before calling this. A locked code otherwise means the delivery can
-- never be confirmed. The public token does not change, so the customer's
-- existing link simply starts showing the new digits.
--
-- The app has already minted and encrypted the replacement; this function only
-- swaps it in and records that it happened.
create or replace function public.reissue_code(
  p_delivery_id uuid,
  p_actor_id    uuid,
  p_code_hash   text,
  p_code_ct     text
)
returns jsonb
language plpgsql
as $$
declare
  d        public.delivery%rowtype;
  c        public.delivery_code%rowtype;
begin
  select * into c from public.delivery_code
    where delivery_id = p_delivery_id
    for update;

  if not found then
    return jsonb_build_object('result', 'not_found');
  end if;

  select * into d from public.delivery where id = p_delivery_id;

  if d.confirmed_at is not null then
    return jsonb_build_object('result', 'already_confirmed');
  end if;

  update public.delivery_code
     set code_hash = p_code_hash,
         code_ct   = p_code_ct,
         attempts  = 0,
         locked    = false,
         reissues  = c.reissues + 1
   where delivery_id = p_delivery_id;

  -- The old code's three failures stay in the log. This is an addition to the
  -- record, not a reset of it.
  insert into public.delivery_event
    (delivery_id, shop_id, type, actor_kind, actor_user_id, payload)
  values
    (p_delivery_id, d.shop_id, 'code_reissued', 'owner', p_actor_id,
     jsonb_build_object('reissue', c.reissues + 1,
                        'after_attempts', c.attempts,
                        'was_locked', c.locked));

  return jsonb_build_object('result', 'reissued', 'reissue', c.reissues + 1);
end;
$$;

revoke execute on function public.reissue_code(uuid, uuid, text, text) from public, anon, authenticated;
grant  execute on function public.reissue_code(uuid, uuid, text, text) to service_role;

